language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t yogeshverma1/docker-react -f Dockerfile.dev .

# script:
#   - docker run yogeshverma1/docker-react npm run test -- --coverage

script:
  - docker run -e CI=yogeshverma1/docker-react npm test
